version: "3.9"
services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  app:
    build:
      context: ./laravel
    volumes:
      - type: bind
        source: ./laravel
        target: /work/backend
  nginx:
    build:
      context: ./nginx
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./laravel
        target: /work/backend
